#!/bin/bash
set -ex

itag=${itag:-247}

for url in $*
do
  video_id=$url
  echo $url|grep "^http" && video_id=$(echo $url|grep -Po '(?<=v=)([\w-]+)')
  channel=$(yt videos --video_id $video_id --part snippet --key channelTitle)
  mkdir -p "$channel"
  pushd "$channel"
  you-get --itag=$itag "https://www.youtube.com/watch?v=$video_id" && echo "https://www.youtube.com/watch?v=$video_id" >> downloaded
  popd
done
