#!/bin/bash
set -x

itag=${itag:-247}

fetch_video(){
  url=$1
  video_id=$url
  playlist=
  channel=
  playlist_id=

  echo $url|grep "^http" && video_id=$(echo $url|grep -Po '(?<=v=)([\w-]+)') && playlist_id=$(echo $url|grep -Po '(?<=list=)([\w-]+)')
  channel=$(yt videos --video_id $video_id --part snippet --key channelTitle)
  [ -z "$playlist_id" ] || playlist=$(yt pl --playlist_id $playlist_id --key title --part snippet)
  [ -z "$channel" ] && echo "Can't find the channel of $video_id" && exit
  mkdir -p "$channel/$playlist"
  pushd "$channel/$playlist"
  touch downloaded
  grep "$url" downloaded && popd && return
  [ -z "$playlist_id" ] || echo $playlist_id > playlist_id
  you-get --itag=$itag "https://www.youtube.com/watch?v=$video_id" && echo "https://www.youtube.com/watch?v=$video_id" >> downloaded
  popd
}

export -f fetch_video
export itag
parallel -k -j 5 --retries 1 --lb fetch_video ::: $*
#for item in $*
#do
#	fetch_video $item
#done
